version: 0.1
phases:
  pre_build:
    commands:
      - echo Hi YAEL =]
      - echo Installing source NPM dependencies...
      - yarn install
      - yarn global add serve
      - serve -v
      - which serve
  build:
    commands:
      - echo Build started on `date`
      - yarn test
      - yarn build
      - (serve -s build&)
      - yarn cy:run
  post_build:
    commands:
        - yarn cy:run
        - ps
        - exit
artifacts:
  files:
    - '**/*'
  base-directory: build
